### ISSUE TITLE
Icon Is Not Ideal

### ISSUE THREAD

**Issue by landry314** [yuttadhammo/BodhiTimer#20]
The icon for this app, how can I put this... it looks like a scrotum. I'm sorry, I just don't like looking at it. I also don't like how thin it is on the top, it feels too delicate for a leaf. Does anyone agree with me?

**Comment by tzugen** [comment]
Thanks for you honest opinion ;)
I haven't thought about the icon, or mostly only that I would like to submit a monochrome version to the frost theme,
but am open to suggestions.

**Comment by baitmooth** [comment]
I saw your try in providing an icon for frost and wanted to help fixing so I'll attach it here.

Since I don't have your app installed i don't know how it looks, but if anyone feels unpleased looking at your icon, consider changing it.

maybe a ginkgo leaf fits? But I also don't know what and why it is now.
[bodhitimer.svg.zip](https://github.com/yuttadhammo/BodhiTimer/files/6618647/bodhitimer.svg.zip)

**Comment by yuttadhammo** [comment]
It's a Bodhi leaf. It's a real leaf from a Bodhi tree, the tree under which
the Buddha became enlightened.

**Comment by baitmooth** [comment]
This makes sense. I have never seen one before and noone mentioned it. Thanks for the explanation.

**Comment by landry314** [comment]
There could be a better image of a bodhi leaf...
